### PR TITLE
Hooked authorisation into Spree Admins only.

### PR DESCRIPTION
**Pull request by parndt**

### CODE REVIEW

**Comment by bricesanchez** [comment]
Thanks @parndt !

**Comment by parndt** [comment]
Note: This doesn't know how to redirect BACK to Refinery once authenticated.

**Comment by parndt** [comment]
I'll leave that as an adventure for you to solve!

**Comment by bricesanchez** [comment]
I've spend all the day to try to find how to access `spree_current_user` method in this connector without a solution.

At this time Refinery doesn't find the current spree user so it redirect to spree login. If i hardcode an admin user, Refinery is able to display the admin.

**Comment by parndt** [comment]
Fixed in #3

**Pull request merged**
